local:
  hosts:
    localhost
  vars:
    ansible_connection: local

lan:
  hosts:
    aldebaran:
      ansible_host: 10.0.0.100
      ansible_user: ru
      ansible_ssh_private_key_file: /home/ru/.ssh/vaio_lan

vps:
  hosts:
    ztv:
      ansible_host: 46.29.237.154
      ansible_user: ru 
      ansible_ssh_private_key_file: /home/ru/.ssh/vaio_ztv

remote:
  children:
    vps:
    lan:
