local:
  hosts:
    localhost:
  vars:
    ansible_connection: local

lan:
  hosts:
    aldebaran:
      ansible_host: 10.0.0.100
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_ssh_private_key_file: "/home/{{ lookup('env', 'USER') }}/.ssh/{{ lookup('env', 'HOSTNAME') }}_lan"
    vaio:
      ansible_host: 10.0.0.27
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_ssh_private_key_file: "/home/{{ lookup('env', 'USER') }}/.ssh/{{ lookup('env', 'HOSTNAME') }}_lan"

vps:
  hosts:
    ztv:
      ansible_host: 46.29.237.154
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_ssh_private_key_file: "/home/{{ lookup('env', 'USER') }}/.ssh/{{ lookup('env', 'HOSTNAME') }}_ztv"

remotes:
  children:
    vps:
    lan:

debops_service_fail2ban:
  children:
    vps:

debops_all_hosts:
  children:
    local:
    remote:
