- hosts: remotes
  become: true
  vars:
  roles:
     # - role:
  tasks:
  - name: add user
    user:
      name: "{{ item.user }}"
      shell: /bin/zsh
      append: true
      create_home: true
      groups: "{{ item.groups }}"
      home: "/home/{{ item.user }}"
      # password: '*'
      # generate_ssh_key: yes
      # ssh_key_bits: 2048
      # ssh_key_file: .ssh/id_rsa
    with_items:
      - { user: "{{ lookup('env', 'USER') }}", groups: "{{ lookup('env', 'USER') }},admin,sudo" }
