---
full_name: Rustam Uzairov
user_name: "{{ ansible_env.USER }}"

git_user: svrvt
git_email: svrvt.zrv@gmail.com

home: "{{ ansible_env.HOME }}"
xdg_config_home: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME + '/.config') }}"
xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + '/.local/share') }}"

# hostname: "{{ ansible_hostname }}"
